apiVersion: v1
kind: Namespace
metadata:
  name: helloworld-operator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-operator
  namespace: helloworld-operator
spec:
  selector:
    matchLabels:
      app: helloworld-operator
  replicas: 1 
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app: helloworld-operator
    spec:
      containers:
      - name: operator
        image: localhost:5000/hw-operator:1.0
        imagePullPolicy: Always